---
title: "Traducciones en Español"
---

Como parte de mi compromiso con la práctica arqueológica equitativa, yo (y mis coautores) nos esforzamos por proporcionar traducciones al español de nuestras publicaciones académicas para que la investigación sea accesible para aquellos que son mínimamente monolingües en español. A continuación se pueden encontrar PDFs o enlaces a materiales complementarios para cada artículo.

As part of my commitment to equitable archaeological practice, I (and my coauthors) endevor to provide Spanish-language translations for our academic publications to make the research accessible to those who are minimally Spanish monolingual. PDF files, or links to supplementary materials for each article can be found below.

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Rivera Prince, Jordi A.** and Amanda Brock Morales. (*in press*). Backdirting: Theorizing Backdirt through Time and Place. *Journal of Field Archaeology.* Special Issue "On Backdirt." Allison Mickell and Christine Luke (editors). Invited Paper. (*peer reviewed*)

Link a la traducción: \[*viene pronto*\]

Milton, Emily, **Jordi A. Rivera Prince**, and Meila Seabrook. (*in press*). Restoring Isotopic Identity Research with Braided Baseintervals. *Bioarchaeology International.* Special Issue "Integrating Chemical Isotopes and Critical Theory in Bioarchaeology." Sara L. Juengst and Matthew C. Velasco (editors). Invited Paper. <https://doi.org/10.5744/bi.2023.0012> (*peer reviewed*)

Link a la traducción: \[*viene pronto*\] Reconciliando Narrativas de Identidad: Creando Espacio de Colaboración con Bases de Referencia Isotópicas.

**Rivera Prince, Jordi A.**, Emily Blackwood, Heather A. Landázuri, Elizabeth L. Leclerc, Monica Barnes, Kristina Douglass, María A. Gutiérrez, Sarah Herr, Kirk A. Maasch, and Daniel H. Sandweiss. (2022). An Intersectional Approach to Equity, Inequity, and Archaeology: A Pathway through Community. Advances in Archaeological Practice 10(4). <https://doi.org/10.1017/aap.2022.26>. (*peer reviewed*)

Link a la traducción: [Supplementary Material 1](https://static.cambridge.org/content/id/urn:cambridge.org:id:article:S2326376822000262/resource/name/S2326376822000262sup001.pdf): Un enfoque interseccional de la equidad, la inequidad y la arqueología: Un camino a través de la comunidad.
