---
title: "Projects"
---

# Current Projects

## **Power in the Hands of Many: A Bioarchaeological Approach to Study Social Inequality in the Ancient Andes, North Coast of Peru (400-200 cal. B.C.)**

Since 2017, I have worked as one of the project bioarchaeologists of the Programa Arqueológico Huanchaco (PAHUAN, PI Dr. Gabriel Prieto, University of Florida). My own research program focuses on the study of the emergence of social inequality in small-scale maritime communities in the ancient Andes. For this purpose, I analyzed human remains and mortuary contexts from the José Olaya - La Iglesia Site (Moche Valley, North Coast of Peru), a cemetery of a small-scale fishing community during the late Early Horizon (400-200 cal. B.C.). Although most research in this period focuses on settlement patterns and architecture analysis, more recent emphasis on domestic settings investigates inequality within groups as part of large social systems, an approach that has revealed important information on past social dynamics. However, little is known concerning how the emergence of inequality affected peoples' daily lives in this region from the perspective of human skeletons and their burial contexts. This project documented skeletal markers of health, lifestyle, nutrition, and stress to investigate whether these traits are potential indicators of social inequality. I also examined the mortuary contexts and grave goods to understand if (and if so, how) social distinction correlates with embodied inequality within the La Iglesia cemetery. This project identified the expression of social inequality in material remains during the late Early Horizon. Ultimately, the focus of this approach was to enhance our anthropological understanding of the emergence of social inequality from the perspective of individuals in small-scale communities.

This project was supported by: The Wenner-Gren Foundation Dissertation Fieldwork Grant (Gr. 10343), The U.S. Fulbright Open Research Grant (Perú), the NSF Graduate Research Fellowship (#1842473), the Ford Predoctoral Fellowship, University of Florida International Center Research Abroad for Doctoral Students, and the UF Elizabeth M. Eddy Summer New Graduate Student Research Award.

## Community Relationships to the Archaeological Past and Archaeological Future in the Virú Valley of Perú

As new project beginning in 2023, this project begins a long-term community-based archaeology program on the coastal Virú Valley of Peru. This project collects local histories and contemporary conceptions of archaeological sites and materials from ancient coastal sites in the Virú Valley, Peru near present-day Puerto Morín. In collecting these stories, this project not only explores relationships between present-day communities and coastal archaeological sites and their role in place making for coastal communities. Furthermore, community members are contributing to archaeological research--in terms of questions and approach--and how they want that archaeological knowledge shared, both academically and back to the community.
