---
title: "Publications"
---

## Papers

**Rivera Prince, Jordi A.** and Amanda Brock Morales (Under Review). Backdirting: Theorizing Backdirt through Time and Place. *Journal of Field Archaeology.* Special Issue "On Backdirt." Allison Mickell and Christine Luke (editors). Invited Paper.

Milton, Emily, **Jordi A. Rivera Prince**, and Meila Seabrook. Restoring Isotopic Identity Research with Braided Baseintervals. *Bioarchaeology International.* Special Issue "Integrating Chemical Isotopes and Critical Theory in Bioarchaeology." Sara L. Juengst and Matthew C. Velasco (editors). Invited Paper.

**Rivera Prince, Jordi A.**, Emily Blackwood, Heather A. Landázuri, Elizabeth L. Leclerc, Monica Barnes, Kristina Douglass, María A. Gutiérrez, Sarah Herr, Kirk A. Maasch, and Daniel H. Sandweiss. (2022). An Intersectional Approach to Equity, Inequity, and Archaeology: A Pathway through Community. *Advances in Archaeological Practice* 10(4). <https://doi.org/10.1017/aap.2022.26>.

Elizabeth Leclerc, Emily Blackwood, Kit M. Hamley, Frankie St. Amand, Heather A. Landázuri, Madeleine Landrum, **Jordi A. Rivera Prince**, Monica Barnes, Kristina Douglass, Maria A. Gutiérrez, Sarah Herr, Kirk A. Maasch, and Daniel H. Sandweiss. (2022). Creating an Equity-Based Seminar in Content and Format: A Case Study and Call to Action. *The SAA Archaeological Record* 22(3): 9-13, 18.

**Rivera Prince, Jordi** y Gabriel Prieto (2022). Primeras aproximaciones bioarqueológicas de una muestra de tumbas Salinar (400-200 cal. a.C.) en la Bahía de Huanchaco: Propuestas y Perspectivas. *Actas del Congreso Nacional de Arqueología VII*, Lima, Perú: 621-631.

Matsumoto, Go, Gabriela de los Ríos Farfán, Fuyuki Tokanai, **Jordi Rivera Prince**, Marie Noguchi, Gabriel Villegas Julca, y Jean Pool Nieves Cordova (2022). Una nueva visión de la Gran Plaza como un escenario animado por diversas actividades rituales. *Actas del Congreso Nacional de Arqueología VII*, Lima, Perú: 85-98.

Matsumoto, Go, Gabriela de los Ríos , **Jordi Rivera Prince**, Marie Noguchi, y Gabriel Villegas Julca (2021). Pasaje ritual de la Gran Plaza en el núcleo ceremonial de Huacas de Sicán. En *Paisaje y territorio en los Andes Centrales: prácticas sociales y dinámicas regionales*, edtado por Luisa Díaz Arriola, Oscar Arias Espinoza, y Atsushi Tamamoto, pp. 115-144. Universidad Nacional Mayor de San Marcos Fondo Editorial, Lima, Perú.

**Rivera Prince, Jordi A.** (2015). Can the Repatriation of the Murry Black Collection be Considered an Apology? Colonial Institutional Culpability in the Indigenous Australian Fight for Decolonization. In Situ; 11-13.

## Edited Volumes

**Rivera Prince, Jordi A**. and Justine M. Shaw (editors). (Re)Creating New Worlds: The Archaeology of Social Transformations. Book Proposal submitted to the University of Utah Press October 2022.

## Technical Reports

**Rivera Prince, Jordi A.** (2019). Restos Humanos de las Huacas de Sicán, Temporada 2019: Proyecto de Investigación Arqueológica Complejo Lambayeque. Burial Report; 155 pages.

**Rivera Prince, Jordi A.** (2017). Interpreting Early Intermediate Period Commingled Remains at La Iglesia, Huanchaco, Peru--Area 13. Burial Report; 75 pages.

**Rivera Prince, Jordi A.** (2017). Restos Humanos de las Huacas de Sicán, Temporada 2017: Proyecto de Investigación Arqueológica Complejo Lambayeque. Burial Report; 49 pages.

**Rivera Prince, Jordi A.** (2017). Pampa la Cruz 2012, Cateo 24: Arqueológico Las Lomas de Huanchaco. Burial Report; 10 pages.

Owsley, Douglas, Kari Bruwelheide, and **Jordi Rivera Prince** (2017). Nebraska State Historical Society: A Report on Human Remains on Loan to the Smithsonian Institution's National Museum of Natural History. Burial Report; 187 pages.

Owsley, Douglas and **Jordi Rivera Prince** (2017). A Male Skull from Bignell, Nebraska (25LN). Burial Report; 4 pages.

**Rivera Prince, Jordi A.**, Douglas Owsley, and Kari Bruwelheide (2016). Human Remains from 44HE1189, St. John's Church, Richmond, VA. Burial Report; 7 pages.

Owsley, Douglas and **Jordi Rivera Prince**. (2017). Equestrian Period Native American Remains from Buffalo, Wyoming. Burial Report; 4 pages.

**Rivera Prince, Jordi A.** (2016). Epigenetic Traits, Computerized Tomography, and Native American Identity. Unpublished Senior Thesis; 147 pages.

## Conference and Panel Participation

### Organized Sessions 

Symposium: Navigating Culture Change: Studies in the (Re)Creation of New Worlds Society for American Archaeology, 87th Annual Meeting, Chicago, IL. Co-Chairs: **Jordi A. Rivera Prince** and Justine Shaw

Symposium: Peering into the Night: Transition, Sociopolitical Organization, and Economic Dynamics after the Dusk of Chavín in the North Central Andes. Society for American Archaeology, 86th Annual Meeting, Virtual Meeting (rescheduled from San Francisco, CA). Co-Chairs: **Jordi A. Rivera Prince** and Patrick Mullins

### Conference Papers 

**Rivera Prince, Jordi A.** (2023) Creating a Fisher's Body: Using Ethnobioarchaeology to Reveal the Caballito de Totora-Body-Fish-Sea Assemblage in Ancient Huanchaco, Peru. Paper. Session "Negotiating Watery Worlds: Impacts and Implications of the Use of Watercraft in Small-Scale Societies" at the Society for American Archaeology 88th Annual Meeting, Portland, OR. April 2023.

**Rivera Prince, Jordi A.** Salinar in the Wake of Chavín: The Emergence of Social Inequality in the North Central Andes at La Iglesia (400-200 cal. BC), Moche Valley, Peru. Paper. Society for American Archaeology, 87th Annual Meeting, Chicago, IL. April 2022.

**Rivera Prince, Jordi A.** (2022). Trauma Profiles of the Late Early Horizon at the La Iglesia Site, Huanchaco, Peru (400 -- 200 cal. BC.). Paper. The Seventh Biennial Meeting of the Society for Amazonian & Andean Studies. Harrisonburg, Virginia.

**Rivera Prince, Jordi A.** and Gabriel Prieto. (2021) A "Salinar Period" Cemetery at the José Olaya Site: Preliminary Demography of a Post-Chavín Maritime Community in the Moche Valley. Paper. Society for American Archaeology, 86th Annual Meeting, Virtual.

**Rivera Prince, Jordi A.** and Gabriel Prieto (2020). Primeras aproximaciones bioarqueologicas de una muestra de tumbas Salinar (400-200 cal. a.C.) en la Bahía de Huanchaco: Propuestas y Perspectivas. Congreso Nacional de Arqueología VII, Lima, Perú.

Matsumoto, Go, Gabriela de los Ríos Farfán, Fuyuki Tokanai, **Jordi Rivera Princ**e, Marie Noguchi, Gabriel Villegas Julca, y Jean Pool Nieves Córdova (2020). Una Nueva Visión de la Gran Plaza Como Escenario Animado por Diversas Actividades Rituales. Congreso Nacional de Arqueología VII, Lima, Perú.

**Rivera Prince, Jordi A.** and Gabriel Prieto (2019). Defining Markers of Occupational Stress in the Ancient Fisherman of Huanchaco, Peru: When Modern Ethnography and Bioarchaeology Intersect. Paper. Society for American Archaeology, 84th Annual Meeting, Albuquerque, NM.

Sutter, Richard, Gabriel Prieto, Celeste M. Gagnon, and **Jordi A. Rivera Prince**. (2019). Horizontality Revisited: Evidence for 3,000 Years of Prehistoric Biocultural Continuity of Fisherfolk at Huanchaco, North Coast of Peru. Paper. Society for American Archaeology, 84th Annual Meeting, Albuquerque, NM.

**Rivera Prince, Jordi A**. (2018). Constructing the Bioarchaeological Record on the Coast of the Moche Valley; How Human Skeletal Analysis at the Jose Olaya Site in Huanchaco Peru Informs the Past, Empowers the Present, and Promotes Future Cultural Patrimony. Paper. Fulbright Enrichment Seminar, Montreal and Ottawa, Canada.
s
### Posters 
**Rivera Prince, Jordi A.**, Gabriel Prieto, and Celeste Gagnon (2018). Disturbing the Ancestors: Interpreting Early Intermediate Period Commingled Remains at La Iglesia, Huanchaco Peru. Poster. Society for American Archaeology, 83rd Annual Meeting, Washington DC. 

### Panels
Learning NAGPRA Collegium Participant (2016). University of Indiana-Bloomington. Collegium included 25 cultural specialists, educational professionals, and students in an effort to create resources for teaching and training on the Native American Graves Protection and Repatriation Act (NAGPRA) to develop methods, format, and content for educational materials about NAGPRA. Funded by the National Science Foundation (Grant #s: 1449465, 1540447).
